import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#08080a',
        surface: '#08080a',
        'surface-dim': '#08080a',
        'surface-bright': '#2c2c30',
        'surface-variant': '#1e1e22',
        'surface-container-lowest': '#060608',
        'surface-container-low': '#0f0f12',
        'surface-container': '#141416',
        'surface-container-high': '#1a1a1e',
        'surface-container-highest': '#222227',
        'surface-tint': '#c6c6c7',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#9ca1a6',
        'on-background': '#e5e1e4',
        outline: '#6b6e72',
        'outline-variant': '#26262b',
        primary: '#ffffff',
        'on-primary': '#121214',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'primary-fixed': '#e2e2e2',
        'on-primary-fixed': '#1a1c1c',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed-variant': '#454747',
        'inverse-primary': '#5d5f5f',
        secondary: '#c1c7cf',
        'on-secondary': '#2b3137',
        'secondary-container': '#24252a',
        'on-secondary-container': '#afb6bd',
        'secondary-fixed': '#dde3eb',
        'on-secondary-fixed': '#161c22',
        'secondary-fixed-dim': '#c1c7cf',
        'on-secondary-fixed-variant': '#41474e',
        tertiary: '#ffffff',
        'on-tertiary': '#233143',
        'tertiary-container': '#d4e4fa',
        'on-tertiary-container': '#576679',
        'tertiary-fixed': '#d4e4fa',
        'on-tertiary-fixed': '#0d1c2d',
        'tertiary-fixed-dim': '#b9c8de',
        'on-tertiary-fixed-variant': '#39485a',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e1e4',
        'inverse-on-surface': '#313032',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
        'display-lg': ['Newsreader', 'serif'],
        'headline-xl': ['Newsreader', 'serif'],
        'headline-lg': ['Newsreader', 'serif'],
        'headline-sm': ['Newsreader', 'serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        h1: ['"Plus Jakarta Sans"', 'sans-serif'],
        h2: ['"Plus Jakarta Sans"', 'sans-serif'],
        h3: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'h1-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        label: ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'h1-mobile': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
      },
      spacing: {
        md: '16px',
        'container-max': '1280px',
        xs: '4px',
        base: '8px',
        sm: '8px',
        lg: '24px',
        xl: '48px',
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'max-width': '1280px',
      },
      keyframes: {
        'panel-in': {
          from: { opacity: '0', transform: 'translateY(0.5rem)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'panel-in': 'panel-in 200ms ease-out',
      },
    },
  },
  plugins: [forms, containerQueries],
}
